[package]
name = "hidpi-widget"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
license = "GPLv3"
readme = "README.md"

[dependencies]
gio = "0.7.0"
glib = "0.8.2"
gtk = { version = "0.7.0", features = ["v3_22"] }
gtk-extras = { git = "https://github.com/pop-os/gtk-extras" }
